[build]
  publish = "dist/drive-flow-web"
  command = "npm run build && cp -r dist/drive-flow-web/browser/* dist/drive-flow-web/"

[build.environment]
  NODE_VERSION = "18"

# Redirect and rewrite rules to support Angular's client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
